spring.application.name:
  sample-api-project
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-id

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true