openapi: 3.0.0
info:
  title: Example REST API
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /api/greet:
    get:
      summary: Greet
      operationId: greet
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
  /api/echo:
    post:
      summary: Echo
      operationId: echo
      requestBody:
        description: Message to echo
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string